### ISSUE TITLE
The SrcMLCppAPI project doesn't build

### ISSUE THREAD

**Issue by patrickfrancis** [abb-iss/SrcML.NET#57]
The SrcMLCppAPI project doesn't build on my computer. There are a couple problems:
1. It can't find srcml.h. The project properties use the SRCMLBINDIR env var in the include path, which isn't the right variable to use.
2. I'm getting an error about command line option /Zp8 not being valid.

The project settings need to be fixed so that the build is portable.

**Comment by cnewman** [comment]
Which environment variable should it use?

**Comment by patrickfrancis** [comment]
Visual Studio provides a number of variables that you can use. You'll want something like $(SolutionDirectory)\External\srcML1.0\include. I'm not sure about the name, though, so you'll have to check the documentation.

**Comment by vinayaugustine** [comment]
https://msdn.microsoft.com/en-us/library/c02as0cs.aspx

**Comment by cnewman** [comment]
@patrickfrancis @vinayaugustine Does this still not build for you? It seems like you might've gotten it working, Pat?

**Comment by patrickfrancis** [comment]
Yes, it worked now for me.

**Comment by cnewman** [comment]
Closing issue for now. Re-open if /ZP8(https://msdn.microsoft.com/en-us/library/xh3e3fd0.aspx) problem crops up again.
